Configure release workflow to create binaries

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,15 +13,32 @@ jobs:
       # Checkout
       - name: Checkout code
         uses: actions/checkout@v2
-      # Make sure that the git tag and Python module version match. Save the version to an output.
-      - name: Check Tag and Version Match
-        id: check_version
+
+      # Install Python dependencies so the module can be run
+      - name: Install Module Dependencies
+        run: python -m pip install -r requirements.txt
+
+      # Get current module version
+      - name: Get Module Version
+        id: get_module_version
         shell: bash
         run: |
-          cd tools
-          bash check_tag_version_match.sh
-          cd ../
-          echo "::set-output name=version::$(git describe --exact-match --tags master)"
+          echo "Module version: $(python run.py --version)"
+          echo "::set-output name=version::$(python run.py --version)"
+
+      # Fail if the tag and version do not match. Also match this to github.ref to make sure we aren't creating a release for an old version
+      - name: Fail on Tag and Version Mismatch
+        if: (!endsWith(github.ref, steps.get_module_version.outputs.version))
+        run: |
+          echo "Ref that triggered release: ${{ github.ref }}"
+          echo "Current module version: ${{ steps.get_module_version.outputs.version }}"
+          exit 1
+
+      # Clear out __pycache__ directories
+      - name: Clear __pycache__
+        shell: bash
+        run: find . -name __pycache__ -type d -print0|xargs -0 rm -r --
+
       # Build the React frontend (will be copied into the python module)
       - name: Build Webapp
         run: |
@@ -29,10 +46,24 @@ jobs:
           npm install
           npm run build
           cd ../
+
       # Zip up the module that now contains has the build webapp
       - name: Zip Module
         shell: pwsh
         run: Compress-Archive -Path .\whos_on_my_network, README.md, requirements.txt, run.py -CompressionLevel Optimal -DestinationPath .\whos_on_my_network.zip
+
+      # Build a binary that uses the default method of scanning
+      - name: Build Binary
+        shell: cmd
+        run: |
+          python -m pip install pyinstaller
+          pyinstaller -y -F --add-data "whos_on_my_network/static";"whos_on_my_network/static/" --distpath ./ -n whos_on_my_network.exe run.py
+
+      # Zip up the binary
+      - name: Zip Module
+        shell: pwsh
+        run: Compress-Archive -Path whos_on_my_network.exe, README.md -CompressionLevel Optimal -DestinationPath .\whos_on_my_network_binary.zip
+
       # Create the release for this version
       - name: Create Release
         id: create_release
@@ -40,13 +71,13 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          tag_name: ${{ steps.get_version.outputs.version }}
-          release_name: Release ${{ steps.check_version.outputs.version }} (${{ github.ref }})
+          tag_name: ${{ steps.get_module_version.outputs.version }}
+          release_name: Release ${{ steps.get_module_version.outputs.version }}
           draft: false
           prerelease: false
+
       # Upload the zip to the created release
-      - name: Upload Release Asset
-        id: upload-release-asset 
+      - name: Upload Built Module to Release
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -54,4 +85,15 @@ jobs:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path: ./whos_on_my_network.zip
           asset_name: whos_on_my_network.zip
+          asset_content_type: application/zip
+
+      # Upload the zip to the created release
+      - name: Upload Binary to Release
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ./whos_on_my_network_binary.zip
+          asset_name: whos_on_my_network_binary.zip
           asset_content_type: application/zip
